name         'opentable-puppetversion'
version '0.1.4'
source       'git://github.com/opentable/puppet-puppetversion.git'
author       'opentable'
summary      'Module for managing the installation and upgrade of puppet'
description  'Install and upgrade puppet consistently across versions and platforms'
project_page 'https://github.com/opentable/puppet-puppetversion'
license      'MIT'
