name         'opentable-puppetversion'
version      '0.1.3'
source       'git://github.com/opentable/puppet-puppetversion.git'
author       'opentable'
summary      'Module for managing the installation and upgrade of puppet'
description  'Install and upgrade puppet consistently across versions and platforms'
project_page 'https://github.com/opentable/puppet-puppetversion'
license      'MIT'
dependency    'puppetlabs/stdlib', '>=3.0.0'
dependency    'puppetlabs/apt', '>=1.4.0'
dependency    'puppetlabs/inifile', '>=1.0.0'
dependency    'stahnma/puppetlabs_yum', '>=0.1.4'
dependency    'opentable/altlib', '>=0.2.0'